### ISSUE TITLE
add folder

### ISSUE THREAD

**Issue by mohdhaekal** [survivejs-translations/webpack-book-id#1]
hello sir .. 
please make one folder. so i can save my translation ...

**Comment by bebraw** [comment]
Hi,

You could commit the translation over the existing text. We have to figure out some nice way to sync changes, though.

See the other translation repos for approaches.

**Comment by mohdhaekal** [comment]
so I directly translate the existing file

**Comment by bebraw** [comment]
Yup. I'll be able to generate the digital version of the book and the site based on that.
